INHERIT: redirects.yml

nav:
###############################################################################
    # Home page
###############################################################################
    - 首页: index.md
###############################################################################
    # Getting started
###############################################################################
    - 教程:
        - 教程介绍: getting-started/README.md
        - 什么是Knative Serving:  getting-started/what-is-knative-serving.md
        - 通过quickstart安装Knative: getting-started/quickstart-install.md
        - 使用Knative Serving:
          - 第一个Knative Service: getting-started/first-service.md
          - 缩容到零: getting-started/first-autoscale.md
          - 流量拆分: getting-started/first-traffic-split.md
        - 使用Knative Eventing:
          - Knative Eventing介绍: getting-started/getting-started-eventing.md
          - 事件源, 代理, 触发器, Sinks: getting-started/first-broker.md
          - 将 Knative Service 作为事件源: getting-started/first-source.md
          - 使用 触发器 and sinks: getting-started/first-trigger.md
        - 接下来?: getting-started/next-steps.md
        - Clean Up: getting-started/clean-up.md
###############################################################################
    # Installing
###############################################################################
    - 安装:
      - 关于安装Knative: install/README.md
      - 通过quickstart安装Knative: install/quickstart-install.md
      # YAML Installation
      - 通过YAML安装Knative:
        - 关于基于YAML的安装: install/yaml-install/README.md
        - 安装 Knative Serving:
          - 通过YAML安装Serving: install/yaml-install/serving/install-serving-with-yaml.md
          - Knative Serving 安装相关文件: install/yaml-install/serving/serving-installation-files.md
        - 安装 Knative Eventing:
          - 通过YAML安装Eventing: install/yaml-install/eventing/install-eventing-with-yaml.md
          - Knative Eventing 安装相关文件: install/yaml-install/eventing/eventing-installation-files.md
      # Operator Installation
      - 通过Knative Operator安装:
        - 通过Operator安装Knative: install/operator/knative-with-operators.md
        - 通过Operator配置Knative: install/operator/configuring-with-operator.md
        - 配置 Knative Serving CRDs: install/operator/configuring-serving-cr.md
        - 配置 Knative Eventing CRDs: install/operator/configuring-eventing-cr.md
      # kn Installation
      - 安装Knative CLI:
        - CLI 工具概述: install/client/README.md
        - 安装 kn: install/client/install-kn.md
        - 自定义 kn: install/client/configure-kn.md
        - kn 插件: install/client/kn-plugins.md
      # Advanced options for Serving
      - 高级安装选项:
        # Istio Installation
        - 为 Knative 安装Istio: install/installing-istio.md
        # Cert-manager Installation
        - 安装 cert-manager: install/installing-cert-manager.md
      # Vendor docs
      - Using a Knative-based offering: install/knative-offerings.md
      # Upgrading Knative
      - 更新Knative:
        - 关于更新Knative: install/upgrade/README.md
        - 检查Knative版本: install/upgrade/check-install-version.md
        - 通过kubectl更新: install/upgrade/upgrade-installation.md
        - 通过Knative Operator更新: install/upgrade/upgrade-installation-with-operator.md
      # Uninstall
      - 卸载Knative: install/uninstall.md
###############################################################################
    # Serving
###############################################################################
    - Serving:
      - 什么是Knative Serving:  getting-started/what-is-knative-serving.md
      - Knative Serving 概述: serving/README.md
      - 自动扩缩:
        - 关于自动扩缩: serving/autoscaling/README.md
        - 支持的自动扩缩类型: serving/autoscaling/autoscaler-types.md
        - 配置 metrics: serving/autoscaling/autoscaling-metrics.md
        - 配置 targets: serving/autoscaling/autoscaling-targets.md
        - 配置缩容到0: serving/autoscaling/scale-to-zero.md
        - 配置并发: serving/autoscaling/concurrency.md
        - 配置每秒请求数 (RPS) target: serving/autoscaling/rps-target.md
        - 配置扩缩容上下界: serving/autoscaling/scale-bounds.md
        - Knative Pod Autoscaler的额外配置: serving/autoscaling/kpa-specific.md
        - 自动扩缩示例程序 - Go: serving/autoscaling/autoscale-go/README.md
        - 配置容器-freezer: serving/autoscaling/container-freezer.md
      # Serving - developer docs
      - 开发者主题:
        - Services:
          - 关于Knative Services: serving/services/README.md
          - 创建一个Service: serving/services/creating-services.md
          - Service指标: serving/services/service-metrics.md
          - 配置私有Services: serving/services/private-services.md
          - Configuring ingress class: serving/services/ingress-class.md
          - Configuring certificate class: serving/services/certificate-class.md
          - Configuring custom domains: serving/services/custom-domains.md
          - Using a custom TLS certificate for DomainMapping: serving/services/byo-certificate.md
          # TODO: Add security section to docs?
          - Configure resource requests and limits: serving/services/configure-requests-limits-services.md
          - HTTPS redirection: serving/services/http-protocol.md
        - Traffic management: serving/traffic-management.md
        - Configuring gradual rollout of traffic to Revisions: serving/rolling-out-latest-revision.md
        - Tag resolution: serving/tag-resolution.md
        - Deploying from private registries: serving/deploying-from-private-registry.md
        - Load balancing:
          - About load balancing: serving/load-balancing/README.md
          - Configuring target burst capacity: serving/load-balancing/target-burst-capacity.md
          - Configuring Activator capacity: serving/load-balancing/activator-capacity.md
        - Revision garbage collection: serving/revision-gc.md
      # Serving - admin docs
      - 集群管理员主题:
        - Kubernetes services: serving/knative-kubernetes-services.md
        - Accessing request traces: serving/accessing-traces.md
        - Enabling requests to Knative services when additional authorization policies are enabled: serving/istio-authorization.md
        - Exclude namespaces from the Knative webhook: serving/webhook-customizations.md
        - Configuring high-availability components: serving/config-ha.md
        - Configuring HTTPS connections: serving/using-a-tls-cert.md
        - Enabling auto-TLS certs: serving/using-auto-tls.md
        - Configuring the ingress gateway: serving/setting-up-custom-ingress-gateway.md
        - Changing the default domain: serving/using-a-custom-domain.md
        - Converting a Kubernetes Deployment to a Knative Service: serving/convert-deployment-to-knative-service.md
        # Serving config
        - Serving configuration:
          - Revision garbage collection: serving/configuration/revision-gc.md
          - Configure Deployment resources: serving/configuration/deployment.md
          - Configuring gradual rollout of traffic to Revisions: serving/configuration/rolling-out-latest-revision-configmap.md
          - Feature and extension flags: serving/configuration/feature-flags.md
          - Configure the Defaults ConfigMap: serving/configuration/config-defaults.md
      # Serving - observability
      - 可观测性:
        - Collecting logs: serving/observability/logging/collecting-logs.md
        - Configuring logging: serving/observability/logging/config-logging.md
        - Collecting metrics: serving/observability/metrics/collecting-metrics.md
        - Knative Serving metrics: serving/observability/metrics/serving-metrics.md
      # Serving - troubleshooting
      - 问题排查:
        - Debugging application issues: serving/troubleshooting/debugging-application-issues.md
###############################################################################
    # Eventing
###############################################################################
    - Eventing:
      - Knative Eventing概述: eventing/README.md
      - Eventing入门: eventing/getting-started.md # do we need this as well as the getting started guide?
      # Eventing - developer docs
      - 开发者主题:
        - Event sources:
          - About event sources: eventing/sources/README.md
          - ApiServerSource:
            - About ApiServerSource: eventing/sources/apiserversource/README.md
            - Creating an ApiServerSource object: eventing/sources/apiserversource/getting-started.md
            - ApiServerSource reference: eventing/sources/apiserversource/reference.md
          - CamelSource: eventing/sources/apache-camel-source/README.md
          - KafkaSource: eventing/sources/kafka-source/README.md
          - PingSource:
            - Creating a PingSource object: eventing/sources/ping-source/README.md
            - PingSource reference: eventing/sources/ping-source/reference.md
        # BYO event source
        - Custom event sources:
          - Custom event sources overview: eventing/custom-event-source/README.md
          - Create a custom event source:
            - Creating an event source overview: eventing/custom-event-source/custom-event-source/README.md
            - Using the Knative sample repository:
              - Configure the sample: eventing/custom-event-source/custom-event-source/sample-repo.md
              - Create a controller: eventing/custom-event-source/custom-event-source/controller.md
              - Create a receive adapter: eventing/custom-event-source/custom-event-source/receive-adapter.md
            - Publishing an event source to your cluster: eventing/custom-event-source/custom-event-source/publish-event-source.md
          - SinkBinding:
            - About SinkBinding: eventing/custom-event-source/sinkbinding/README.md
            - Create a SinkBinding: eventing/custom-event-source/sinkbinding/create-a-sinkbinding.md
            - SinkBinding reference: eventing/custom-event-source/sinkbinding/reference.md
          - ContainerSource:
            - Create a ContainerSource: eventing/custom-event-source/containersource/README.md
            - ContainerSource Reference: eventing/custom-event-source/containersource/reference.md
        - Event sinks:
          - About sinks: eventing/sinks/README.md
          - KafkaSink: eventing/sinks/kafka-sink.md
        - Handling delivery failure: eventing/event-delivery.md
        - Flows:
          - About flows: eventing/flows/README.md
          - Parallel: eventing/flows/parallel.md
          - Sequence:
            - About Sequences: eventing/flows/sequence/README.md
            - Displaying Sequence output: eventing/flows/sequence/sequence-reply-to-event-display/README.md
            - Using Sequences in series: eventing/flows/sequence/sequence-reply-to-sequence/README.md
            - Create additional events: eventing/flows/sequence/sequence-terminal/README.md
            - Using with Broker and Trigger: eventing/flows/sequence/sequence-with-broker-trigger/README.md
        - Channels:
          - About Channels: eventing/channels/README.md
          - Channel types and defaults: eventing/channels/channel-types-defaults.md
          - Creating a Channel using cluster or namespace defaults: eventing/channels/create-default-channel.md
          - Available Channels: eventing/channels/channels-crds.md
          - Subscriptions: eventing/channels/subscriptions.md
        - Sugar Controller: eventing/sugar/README.md
        - Brokers:
          - About Brokers: eventing/broker/README.md
          - Using the Event registry: eventing/event-registry.md # does this make sense here since it mentions being used with brokers and triggers?
          - Creating a Broker: eventing/broker/create-mtbroker.md
          - Triggers: eventing/broker/triggers/README.md
          - Broker configuration example: eventing/broker/example-mtbroker.md
          - Knative Kafka Broker: eventing/broker/kafka-broker/README.md
          - RabbitMQ Broker: eventing/broker/rabbitmq-broker/README.md
        - Accessing CloudEvent traces: eventing/accessing-traces.md
      # Eventing - admin docs
      - 集群管理员主题:
        # Eventing config
        - Eventing configuration:
          - Configure Channel defaults: eventing/configuration/channel-configuration.md
          - Configure Broker defaults: eventing/configuration/broker-configuration.md
          - Configure Kafka Channel defaults: eventing/configuration/kafka-channel-configuration.md
          - Configure event source defaults: eventing/configuration/sources-configuration.md
      # Eventing - observability
      - 可观测性:
        - Collecting logs: eventing/observability/logging/collecting-logs.md
        - Configuring logging: eventing/observability/logging/config-logging.md
        - Collecting metrics: eventing/observability/metrics/collecting-metrics.md
        - Knative Eventing metrics: eventing/observability/metrics/eventing-metrics.md
      # Eventing - troubleshooting
      - 问题排查:
        - Debugging: eventing/troubleshooting/README.md
      - 实验性特性:
        - About Eventing experimental features: eventing/experimental-features/README.md
        - DeliverySpec.Timeout field: eventing/experimental-features/delivery-timeout.md
        - DeliverySpec.RetryAfterMax field: eventing/experimental-features/delivery-retryafter.md
        - New Trigger Filters: eventing/experimental-features/new-trigger-filters.md
        - KReference.Group field: eventing/experimental-features/kreference-group.md
        - Knative reference mapping: eventing/experimental-features/kreference-mapping.md
        - Strict Subscriber: eventing/experimental-features/strict-subscriber.md
###############################################################################
    # Code samples
###############################################################################
    - 代码示例:
      - 代码示例概述: samples/README.md
      - Serving示例代码: samples/serving.md
      - Eventing示例代码: samples/eventing.md
    # Reference docs
    - 参考:
      - 参考概述: reference/README.md
      - API:
        - Serving: reference/api/serving-api.md
        - Eventing: reference/api/eventing-api.md
      - Client: reference/client/README.md
      - Concepts:
        - Duck types: reference/concepts/duck-typing.md
      - Security: reference/security/README.md
    - 社区:
      - Welcome to the community: community/README.md
      - Contribute to Knative: community/contributing.md
      - About the community: community/about.md
    - 关于:
      - Testimonials: about/testimonials.md
      - Case studies:
        - deepc: about/case-studies/deepc.md
        - Outfit7: about/case-studies/outfit7.md
        - Puppet: about/case-studies/puppet.md
#    - Blog: /blog/
